In [1]:
import pandas as pd
from io import StringIO

csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''

df = pd.read_csv(StringIO(csv_data))
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [2]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

Missing Value Handling

1. Remove Missing Value

    Advantage: convinent

    Disadvantage: may end up removing too many data to make analysis, or
    losing valuable information

In [3]:
df.dropna(axis=0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [4]:
df.dropna(axis=1)

      A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

2. Impute Missing Value

In [5]:
from sklearn.impute import SimpleImputer
import numpy as np

imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

Categorical Data Encoding

In [6]:
import pandas as pd
df = pd.DataFrame([
    ['green', 'M', 10.1, 'class2'],
    ['red', 'L', 13.5, 'class1'],
    ['blue', 'XL', 15.3, 'class2']])
df.columns = ['color', 'size', 'price', 'classlabel']
df

   color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [7]:
# ordinal features transformation
size_mapping = {'XL': 3,
    'L': 2,
    'M': 1}

df['size'] = df['size'].map(size_mapping)
df

   color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [8]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}

df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: str

In [9]:
class_mapping = {label: idx for idx, label in
            enumerate(np.unique(df['classlabel']))}

class_mapping

{'class1': 0, 'class2': 1}

In [10]:
df['classlabel'].map(class_mapping)

0    1
1    0
2    1
Name: classlabel, dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
y

array([1, 0, 1])

In [12]:
class_le.inverse_transform(y)

array(['class2', 'class1', 'class2'], dtype=object)

In [15]:
# one hot encoding

from sklearn.preprocessing import OneHotEncoder

X = df[['color', 'size', 'price']].values
color_ohe = OneHotEncoder()
color_ohe.fit_transform(X[:, 0].reshape(-1, 1)).toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [16]:
from sklearn.compose import ColumnTransformer
X = df[['color', 'size', 'price']].values
c_transf = ColumnTransformer([
    ('onehot', OneHotEncoder(), [0]),
    ('nothing', 'passthrough', [1, 2])
    ])
c_transf.fit_transform(X).astype(float)

array([[ 0. ,  1. ,  0. ,  1. , 10.1],
       [ 0. ,  0. ,  1. ,  2. , 13.5],
       [ 1. ,  0. ,  0. ,  3. , 15.3]])

In [17]:
df = pd.DataFrame([['green', 'M', 10.1,
    'class2'],
    ['red', 'L', 13.5,
    'class1'],
    ['blue', 'XL', 15.3,
    'class2']])
df.columns = ['color', 'size', 'price',
    'classlabel']

df

   color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [19]:
# Alternative of one-hot-encoding if not knowing absolute size to use

df["x > M"] = df["size"].apply(
    lambda x:  1 if x in {"L", "XL"} else 0
)

df['x > L'] = df['size'].apply(
    lambda x: 1 if x == 'XL' else 0)
del df["size"]
df

   color  price classlabel  x > M  x > L
0  green   10.1     class2      0      0
1    red   13.5     class1      1      0
2   blue   15.3     class2      1      1