In [35]:
import pandas as pd
from io import StringIO

csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''

df = pd.read_csv(StringIO(csv_data))
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [36]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

Missing Value Handling

1. Remove Missing Value

    Advantage: convinent

    Disadvantage: may end up removing too many data to make analysis, or
    losing valuable information

In [37]:
df.dropna(axis=0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [38]:
df.dropna(axis=1)

      A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

2. Impute Missing Value

In [39]:
from sklearn.impute import SimpleImputer
import numpy as np

imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

Categorical Data Encoding

In [40]:
import pandas as pd
df = pd.DataFrame([
    ['green', 'M', 10.1, 'class2'],
    ['red', 'L', 13.5, 'class1'],
    ['blue', 'XL', 15.3, 'class2']])
df.columns = ['color', 'size', 'price', 'classlabel']
df

   color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [41]:
# ordinal features transformation
size_mapping = {'XL': 3,
    'L': 2,
    'M': 1}

df['size'] = df['size'].map(size_mapping)
df

   color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [42]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}

df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: str

In [43]:
class_mapping = {label: idx for idx, label in
            enumerate(np.unique(df['classlabel']))}

class_mapping

{'class1': 0, 'class2': 1}

In [44]:
df['classlabel'].map(class_mapping)

0    1
1    0
2    1
Name: classlabel, dtype: int64

In [45]:
from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
y

array([1, 0, 1])

In [46]:
class_le.inverse_transform(y)

array(['class2', 'class1', 'class2'], dtype=object)